server:
  port: 8081

spring:
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
